In [1]:
s1 = 'Chamelon'
s2 = 'ham'

s2 in s1

True

In [2]:
s1[-4:]

'elon'

In [3]:
print(s1.index('a'))

2

In [17]:
l1 = ['r', 'Is', '>', ' < ', 'g ', '?']
x = ''
print(x.join(l1))

rIs> < g ?

In [19]:
words = {
    'animal': 'True',
    'coffee': 'False'
}

print(words['coffee'])

False

In [25]:
for key, value in words.items():
    if value == 'True': 
        print(key + ' starts with a vowel')
    else: 
        print(key + ' does not start with a vowel')

animal starts with a vowel
coffee does not start with a vowel

## section 3.2 punk IPA API

In [28]:
url = 'https://api.punkapi.com/v2/beers?brewed_before=12-2008&abv_gt=8'
import requests
response = requests.get(url)
response.ok

True

In [68]:
jsonresponse = response.json()
jsonresponse

[{'id': 37,
  'name': 'Zephyr',
  'tagline': 'There’s A Storm Brewing.',
  'first_brewed': '10/2008',
  'description': 'A 9.2% Double IPA aged for 21 months in a 1965 Invergordon cask with 30 kg of fresh highland strawberries. This beer is a riot of whisky, caramel and strawberry, all tempered by a toe curling bitterness enducing rapture in all who taste it. Who needs champagne?',
  'image_url': 'https://images.punkapi.com/v2/37.png',
  'abv': 12.5,
  'ibu': 125,
  'target_fg': 1016,
  'target_og': 1087,
  'ebc': 40,
  'srm': 20,
  'ph': 4.4,
  'attenuation_level': 81.2,
  'volume': {'value': 20, 'unit': 'liters'},
  'boil_volume': {'value': 25, 'unit': 'liters'},
  'method': {'mash_temp': [{'temp': {'value': 65, 'unit': 'celsius'},
     'duration': 75}],
   'fermentation': {'temp': {'value': 21, 'unit': 'celsius'}},
   'twist': 'Oak chips: 15g, Fresh strawberries: 3kg'},
  'ingredients': {'malt': [{'name': 'Extra Pale',
     'amount': {'value': 6.3, 'unit': 'kilograms'}},
    {'name': 'Caramalt', 'amount': {'value': 0.38, 'unit': 'kilograms'}},
    {'name': 'Crystal 150', 'amount': {'value': 0.29, 'unit': 'kilograms'}}],
   'hops': [{'name': 'Columbus Extract',
     'amount': {'value': 31, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Columbus',
     'amount': {'value': 19.5, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Columbus',
     'amount': {'value': 19.5, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Centennial',
     'amount': {'value': 19.5, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Simcoe',
     'amount': {'value': 19.5, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Columbus',
     'amount': {'value': 19.5, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'},
    {'name': 'Centennial',
     'amount': {'value': 19.5, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'},
    {'name': 'Centennial',
     'amount': {'value': 115.5, 'unit': 'grams'},
     'add': 'dry hop',
     'attribute': 'aroma'},
    {'name': 'Columbus',
     'amount': {'value': 96, 'unit': 'grams'},
     'add': 'dry hop',
     'attribute': 'aroma'},
    {'name': 'Simcoe',
     'amount': {'value': 96, 'unit': 'grams'},
     'add': 'dry hop',
     'attribute': 'aroma'},
    {'name': 'Amarillo',
     'amount': {'value': 77, 'unit': 'grams'},
     'add': 'dry hop',
     'attribute': 'aroma'}],
   'yeast': 'Wyeast 1272 - American Ale II™'},
  'food_pairing': ['Poached eggs and smoked salmon',
   'Salt and pepper squid',
   'Key Lime Pie'],
  'brewers_tips': 'Rack into a secondary fermenter and add your strawberries. Use a blow-off rather than an airlock as the fermentation can get pretty wild as the yeast starts using the sugar from the strawberries.',
  'contributed_by': 'Sam Mason <samjbmason>'},
 {'id': 52,
  'name': 'Paradox Islay',
  'tagline': 'Ubiquitous Imperial Stout.',
  'first_brewed': '04/2007',
  'description': 'In 2006 James and Martin hijacked a beer dinner run by Michael Jackson, the acclaimed beer and whisky writer, and convinced him to taste one of their home brews. This was a defining moment in BrewDog prehistory, and that beer was the first incarnation of the ubiquitous Paradox. Aged in a variety of casks over the years, Paradox is dark, decadent and encapsulating. Can be enjoyed fresh; phenomenal when aged.',
  'image_url': 'https://images.punkapi.com/v2/52.png',
  'abv': 10,
  'ibu': 55,
  'target_fg': 1014,
  'target_og': 1090,
  'ebc': 300,
  'srm': 152,
  'ph': 4.4,
  'attenuation_level': 84.4,
  'volume': {'value': 20, 'unit': 'liters'},
  'boil_volume': {'value': 25, 'unit': 'liters'},
  'method': {'mash_temp': [{'temp': {'value': 65, 'unit': 'celsius'},
     'duration': 90}],
   'fermentation': {'temp': {'value': 21, 'unit': 'celsius'}},
   'twist': 'Try ageing on oak chips, infusing with rum raisins, or vanilla pods'},
  'ingredients': {'malt': [{'name': 'Extra Pale',
     'amount': {'value': 4.5, 'unit': 'kilograms'}},
    {'name': 'Caramalt', 'amount': {'value': 0.55, 'unit': 'kilograms'}},
    {'name': 'Munich', 'amount': {'value': 0.33, 'unit': 'kilograms'}},
    {'name': 'Flaked Oats', 'amount': {'value': 1.35, 'unit': 'kilograms'}},
    {'name': 'Dark Crystal', 'amount': {'value': 0.55, 'unit': 'kilograms'}},
    {'name': 'Carafa Special Malt Type 1',
     'amount': {'value': 0.18, 'unit': 'kilograms'}},
    {'name': 'Carafa Special Malt Type 3',
     'amount': {'value': 0.33, 'unit': 'kilograms'}}],
   'hops': [{'name': 'Columbus',
     'amount': {'value': 75, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Columbus',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Saaz',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'},
    {'name': 'First Gold',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'}],
   'yeast': 'Wyeast 1272 - American Ale II™'},
  'food_pairing': ['Ancho chilli beef taco',
   'Chocolate gateaux',
   'Rum poached pears with dark chocolate sauce'],
  'brewers_tips': 'The beauty of this beer is in how brilliantly it lends itself to infusing or ageing. Experiment with different additions when the beer is ageing, taste it regularly to gauge its progress, and make sure you package it at its peak.',
  'contributed_by': 'Sam Mason <samjbmason>'},
 {'id': 58,
  'name': 'Coffee Imperial Stout',
  'tagline': 'Beats a Cup of Joe.',
  'first_brewed': '11/2008',
  'description': 'This beer was released as both as "Danish Beerhouse Coffee Imperial Stout" and "BrewDog Coffee Imperial Stout". Deep, dark, roasted flavours make this a perfect Sunday brunch beer.',
  'image_url': 'https://images.punkapi.com/v2/58.png',
  'abv': 9,
  'ibu': 65,
  'target_fg': 1019,
  'target_og': 1080,
  'ebc': 97,
  'srm': 49,
  'ph': 4.4,
  'attenuation_level': 76,
  'volume': {'value': 20, 'unit': 'liters'},
  'boil_volume': {'value': 25, 'unit': 'liters'},
  'method': {'mash_temp': [{'temp': {'value': 64, 'unit': 'celsius'},
     'duration': 90}],
   'fermentation': {'temp': {'value': 19, 'unit': 'celsius'}},
   'twist': 'Coffee added after boil. Aged on French oak chips., Dark muscovado sugar: 312.5g for 20mins'},
  'ingredients': {'malt': [{'name': 'Extra Pale',
     'amount': {'value': 7.5, 'unit': 'kilograms'}},
    {'name': 'Dark Crystal', 'amount': {'value': 0.63, 'unit': 'kilograms'}},
    {'name': 'Chocolate', 'amount': {'value': 0.31, 'unit': 'kilograms'}},
    {'name': 'Roast Barley', 'amount': {'value': 0.31, 'unit': 'kilograms'}}],
   'hops': [{'name': 'Chinook',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Galena',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Galena',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'},
    {'name': 'First Gold',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'},
    {'name': 'Coffee',
     'amount': {'value': 9.4, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'},
    {'name': 'Coffee',
     'amount': {'value': 9.4, 'unit': 'grams'},
     'add': 'dry hop',
     'attribute': 'aroma'}],
   'yeast': 'Wyeast 1056 - American Ale™'},
  'food_pairing': ['Gooey chocolate brownies',
   'Chicken fried steak with cheesy mash',
   'Spicy chicken empanadas'],
  'brewers_tips': 'Grind the coffee as if making an espresso to really get the most out of it.',
  'contributed_by': 'Sam Mason <samjbmason>'},
 {'id': 149,
  'name': 'AB:03',
  'tagline': 'Barrel-Aged Imperial Ale.',
  'first_brewed': '09/2008',
  'description': 'This Abstrakt started life as a simple imperial Ale, but upon the addition of fresh Scottish raspberries and strawberries, and left to mature for 2 years in Invergordon whisky casks that had held whisky for over 40 years, this beer transcended into something new.',
  'image_url': 'https://images.punkapi.com/v2/149.png',
  'abv': 10.5,
  'ibu': 14,
  'target_fg': 1013,
  'target_og': 1093,
  'ebc': None,
  'srm': None,
  'ph': 4.4,
  'attenuation_level': 80,
  'volume': {'value': 20, 'unit': 'liters'},
  'boil_volume': {'value': 25, 'unit': 'liters'},
  'method': {'mash_temp': [{'temp': {'value': 65, 'unit': 'celsius'},
     'duration': 90}],
   'fermentation': {'temp': {'value': 19, 'unit': 'celsius'}},
   'twist': 'Strawberries: 1kg, Raspberries: 1kg, Oak Chips: 75g'},
  'ingredients': {'malt': [{'name': 'Extra Pale',
     'amount': {'value': 8, 'unit': 'kilograms'}}],
   'hops': [{'name': 'Magnum',
     'amount': {'value': 66.7, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'}],
   'yeast': 'Wyeast 1056 - American Ale™'},
  'food_pairing': ['Haggis spring rolls',
   'Honey glazed duck breast',
   'Cranachan'],
  'brewers_tips': 'Add your hops with five minutes of the boil left in a nod to the great lambic producers of Belgium.',
  'contributed_by': 'Sam Mason <samjbmason>'}]

In [84]:
hops = jsonresponse[1]['ingredients']['hops']
hops

[{'name': 'Columbus',
  'amount': {'value': 75, 'unit': 'grams'},
  'add': 'start',
  'attribute': 'bitter'},
 {'name': 'Columbus',
  'amount': {'value': 25, 'unit': 'grams'},
  'add': 'middle',
  'attribute': 'flavour'},
 {'name': 'Saaz',
  'amount': {'value': 25, 'unit': 'grams'},
  'add': 'end',
  'attribute': 'flavour'},
 {'name': 'First Gold',
  'amount': {'value': 25, 'unit': 'grams'},
  'add': 'end',
  'attribute': 'flavour'}]

In [92]:
for i in hops:
    ipa = i
    for k, v in ipa.items():
        print(v)

Columbus
{'value': 75, 'unit': 'grams'}
start
bitter
Columbus
{'value': 25, 'unit': 'grams'}
middle
flavour
Saaz
{'value': 25, 'unit': 'grams'}
end
flavour
First Gold
{'value': 25, 'unit': 'grams'}
end
flavour

## Exc 3.3

In [145]:
vars = ['tid=*', 'civilstand=U']   

def construct_link(x, y):
    start_url = 'https://api.statbank.dk/v1/data/'
    final_url = start_url + x + '/JSONSTAT?' + y[0] + '&' + y[1]
    print(final_url)
    
construct_link('FOLK1A', vars)

https://api.statbank.dk/v1/data/FOLK1A/JSONSTAT?tid=*&civilstand=U

In [149]:
vars2 = ['tid=*', 'barnkon=P']
construct_link('FOD', vars2)

https://api.statbank.dk/v1/data/FOD/JSONSTAT?tid=*&barnkon=P

In [150]:
url2 = 'https://api.statbank.dk/v1/data/FOD/JSONSTAT?tid=*&barnkon=P'
response2 = requests.get(url2)
response2.ok

True

In [151]:
jsonresponse2 = response2.json()
jsonresponse2

{'dataset': {'dimension': {'BARNKON': {'label': 'barnets køn',
    'category': {'index': {'P': 0}, 'label': {'P': 'Piger'}}},
   'ContentsCode': {'label': 'Indhold',
    'category': {'index': {'FOD': 0},
     'label': {'FOD': 'Levendefødte'},
     'unit': {'FOD': {'base': 'antal', 'decimals': 0}}}},
   'Tid': {'label': 'tid',
    'category': {'index': {'1973': 0,
      '1974': 1,
      '1975': 2,
      '1976': 3,
      '1977': 4,
      '1978': 5,
      '1979': 6,
      '1980': 7,
      '1981': 8,
      '1982': 9,
      '1983': 10,
      '1984': 11,
      '1985': 12,
      '1986': 13,
      '1987': 14,
      '1988': 15,
      '1989': 16,
      '1990': 17,
      '1991': 18,
      '1992': 19,
      '1993': 20,
      '1994': 21,
      '1995': 22,
      '1996': 23,
      '1997': 24,
      '1998': 25,
      '1999': 26,
      '2000': 27,
      '2001': 28,
      '2002': 29,
      '2003': 30,
      '2004': 31,
      '2005': 32,
      '2006': 33,
      '2007': 34,
      '2008': 35,
      '2009': 36,
      '2010': 37,
      '2011': 38,
      '2012': 39,
      '2013': 40,
      '2014': 41,
      '2015': 42,
      '2016': 43,
      '2017': 44},
     'label': {'1973': '1973',
      '1974': '1974',
      '1975': '1975',
      '1976': '1976',
      '1977': '1977',
      '1978': '1978',
      '1979': '1979',
      '1980': '1980',
      '1981': '1981',
      '1982': '1982',
      '1983': '1983',
      '1984': '1984',
      '1985': '1985',
      '1986': '1986',
      '1987': '1987',
      '1988': '1988',
      '1989': '1989',
      '1990': '1990',
      '1991': '1991',
      '1992': '1992',
      '1993': '1993',
      '1994': '1994',
      '1995': '1995',
      '1996': '1996',
      '1997': '1997',
      '1998': '1998',
      '1999': '1999',
      '2000': '2000',
      '2001': '2001',
      '2002': '2002',
      '2003': '2003',
      '2004': '2004',
      '2005': '2005',
      '2006': '2006',
      '2007': '2007',
      '2008': '2008',
      '2009': '2009',
      '2010': '2010',
      '2011': '2011',
      '2012': '2012',
      '2013': '2013',
      '2014': '2014',
      '2015': '2015',
      '2016': '2016',
      '2017': '2017'}}},
   'id': ['BARNKON', 'ContentsCode', 'Tid'],
   'size': [1, 1, 45],
   'role': {'metric': ['ContentsCode'], 'time': ['Tid']}},
  'label': 'Levendefødte efter barnets køn, Indhold og tid',
  'source': 'Danmarks Statistik',
  'updated': '2018-02-21T07:00:00Z',
  'value': [34996,
   34771,
   35260,
   31533,
   30055,
   30161,
   28909,
   27941,
   25972,
   25595,
   24821,
   25228,
   26284,
   26878,
   27142,
   28520,
   29876,
   30813,
   31353,
   32914,
   32760,
   34027,
   33885,
   32819,
   32899,
   32116,
   32341,
   32652,
   31961,
   31109,
   31441,
   31539,
   31459,
   31580,
   31267,
   31507,
   30557,
   30946,
   28984,
   28131,
   27283,
   27616,
   28357,
   29833,
   29930]}}

In [164]:
import pandas as pd
data = pd.DataFrame.from_dict(jsonresponse2, orient="columns")
data.values

array([[{'BARNKON': {'label': 'barnets køn', 'category': {'index': {'P': 0}, 'label': {'P': 'Piger'}}}, 'ContentsCode': {'label': 'Indhold', 'category': {'index': {'FOD': 0}, 'label': {'FOD': 'Levendefødte'}, 'unit': {'FOD': {'base': 'antal', 'decimals': 0}}}}, 'Tid': {'label': 'tid', 'category': {'index': {'1973': 0, '1974': 1, '1975': 2, '1976': 3, '1977': 4, '1978': 5, '1979': 6, '1980': 7, '1981': 8, '1982': 9, '1983': 10, '1984': 11, '1985': 12, '1986': 13, '1987': 14, '1988': 15, '1989': 16, '1990': 17, '1991': 18, '1992': 19, '1993': 20, '1994': 21, '1995': 22, '1996': 23, '1997': 24, '1998': 25, '1999': 26, '2000': 27, '2001': 28, '2002': 29, '2003': 30, '2004': 31, '2005': 32, '2006': 33, '2007': 34, '2008': 35, '2009': 36, '2010': 37, '2011': 38, '2012': 39, '2013': 40, '2014': 41, '2015': 42, '2016': 43, '2017': 44}, 'label': {'1973': '1973', '1974': '1974', '1975': '1975', '1976': '1976', '1977': '1977', '1978': '1978', '1979': '1979', '1980': '1980', '1981': '1981', '1982': '1982', '1983': '1983', '1984': '1984', '1985': '1985', '1986': '1986', '1987': '1987', '1988': '1988', '1989': '1989', '1990': '1990', '1991': '1991', '1992': '1992', '1993': '1993', '1994': '1994', '1995': '1995', '1996': '1996', '1997': '1997', '1998': '1998', '1999': '1999', '2000': '2000', '2001': '2001', '2002': '2002', '2003': '2003', '2004': '2004', '2005': '2005', '2006': '2006', '2007': '2007', '2008': '2008', '2009': '2009', '2010': '2010', '2011': '2011', '2012': '2012', '2013': '2013', '2014': '2014', '2015': '2015', '2016': '2016', '2017': '2017'}}}, 'id': ['BARNKON', 'ContentsCode', 'Tid'], 'size': [1, 1, 45], 'role': {'metric': ['ContentsCode'], 'time': ['Tid']}}],
       ['Levendefødte efter barnets køn, Indhold og tid'],
       ['Danmarks Statistik'],
       ['2018-02-21T07:00:00Z'],
       [list([34996, 34771, 35260, 31533, 30055, 30161, 28909, 27941, 25972, 25595, 24821, 25228, 26284, 26878, 27142, 28520, 29876, 30813, 31353, 32914, 32760, 34027, 33885, 32819, 32899, 32116, 32341, 32652, 31961, 31109, 31441, 31539, 31459, 31580, 31267, 31507, 30557, 30946, 28984, 28131, 27283, 27616, 28357, 29833, 29930])]],
      dtype=object)

## Exc 4 pandas

In [203]:
import pandas as pd 
data = pd.read_csv('https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/by_year/1864.csv.gz',
                  compression = 'gzip', header=None)
mydf = pd.DataFrame(data.iloc[:,0:4])

In [204]:
mydf.columns = ['station identifier', 'data', 'observation type', 'obs values']
mydf

      station identifier      data observation type  obs values
0            ITE00100550  18640101             TMAX          10
1            ITE00100550  18640101             TMIN         -23
2            ITE00100550  18640101             PRCP          25
3            ASN00079028  18640101             PRCP           0
4            USC00064757  18640101             PRCP         119
5            SF000208660  18640101             PRCP           0
6            ASN00089000  18640101             PRCP           0
7            SWE00100003  18640101             PRCP           0
8            ASN00086071  18640101             TMAX         214
9            ASN00086071  18640101             TMIN         101
10           ASN00086071  18640101             PRCP           0
11           USP00CA0003  18640101             PRCP           0
12           USC00189674  18640101             PRCP           0
13           USC00144559  18640101             PRCP           0
14           USC00144559  18640101             SNOW           0
15           CA006158350  18640101             TMAX          11
16           CA006158350  18640101             TMIN        -133
17           CA006158350  18640101             PRCP           5
18           CA006158350  18640101             SNOW           5
19           HRE00105189  18640101             PRCP         189
20           ASN00067054  18640101             PRCP          61
21           ASN00081003  18640101             PRCP           0
22           ASN00078037  18640101             PRCP           0
23           ASN00070037  18640101             PRCP           0
24           EIE00101859  18640101             TMAX          94
25           EIE00101859  18640101             TMIN          11
26           EIE00101859  18640101             PRCP          82
27           ASN00040214  18640101             PRCP           3
28           BE000006447  18640101             TMAX         -23
29           BE000006447  18640101             TMIN         -36
...                  ...       ...              ...         ...
27318        ASN00066062  18641231             TMAX         223
27319        ASN00066062  18641231             TMIN         172
27320        ASN00066062  18641231             PRCP          41
27321        ASN00023000  18641231             PRCP           0
27322        SW000010537  18641231             PRCP           0
27323        ASN00022018  18641231             PRCP           0
27324        AU000005901  18641231             TMAX         -28
27325        AU000005901  18641231             TMIN         -79
27326        GM000004204  18641231             TMAX         -34
27327        GM000004204  18641231             TMIN        -119
27328        GM000004204  18641231             PRCP           0
27329        ASN00075048  18641231             PRCP           0
27330        UK000047811  18641231             TMAX          40
27331        UK000047811  18641231             TMIN         -14
27332        UK000047811  18641231             PRCP           0
27333        HR000142360  18641231             PRCP           0
27334        ASN00084016  18641231             PRCP          18
27335        ITE00100553  18641231             PRCP           0
27336        ITE00100552  18641231             PRCP           0
27337        ITE00105250  18641231             PRCP           0
27338        USP00CA0001  18641231             PRCP         157
27339        ASN00090015  18641231             TMAX         239
27340        ASN00090015  18641231             TMIN         128
27341        UK000056225  18641231             TMAX          16
27342        UK000056225  18641231             TMIN         -19
27343        UK000056225  18641231             PRCP           3
27344        ASN00026026  18641231             PRCP           0
27345        ASN00089049  18641231             PRCP           0
27346        SZ000006717  18641231             TMAX         -62
27347        SZ000006717  18641231             TMIN        -105

[27348 rows x 4 columns]

In [246]:
newdf = mydf.loc[(mydf['station identifier'] == 'ITE00100550') & (mydf['observation type'] == 'TMAX')]
newdf

      station identifier      data observation type  obs values
0            ITE00100550  18640101             TMAX          10
75           ITE00100550  18640102             TMAX           8
152          ITE00100550  18640103             TMAX         -28
227          ITE00100550  18640104             TMAX           0
305          ITE00100550  18640105             TMAX         -19
383          ITE00100550  18640106             TMAX         -13
460          ITE00100550  18640107             TMAX          -4
538          ITE00100550  18640108             TMAX          13
618          ITE00100550  18640109             TMAX          13
695          ITE00100550  18640110             TMAX           6
770          ITE00100550  18640111             TMAX         -15
847          ITE00100550  18640112             TMAX         -25
924          ITE00100550  18640113             TMAX         -43
1002         ITE00100550  18640114             TMAX         -50
1080         ITE00100550  18640115             TMAX         -31
1158         ITE00100550  18640116             TMAX         -25
1236         ITE00100550  18640117             TMAX         -63
1311         ITE00100550  18640118             TMAX         -50
1388         ITE00100550  18640119             TMAX         -16
1465         ITE00100550  18640120             TMAX          -9
1542         ITE00100550  18640121             TMAX          -4
1619         ITE00100550  18640122             TMAX           9
1696         ITE00100550  18640123             TMAX          25
1774         ITE00100550  18640124             TMAX          39
1850         ITE00100550  18640125             TMAX          38
1928         ITE00100550  18640126             TMAX          53
2006         ITE00100550  18640127             TMAX          44
2084         ITE00100550  18640128             TMAX          46
2161         ITE00100550  18640129             TMAX          35
2238         ITE00100550  18640130             TMAX          31
...                  ...       ...              ...         ...
25095        ITE00100550  18641202             TMAX          73
25171        ITE00100550  18641203             TMAX          65
25245        ITE00100550  18641204             TMAX          56
25320        ITE00100550  18641205             TMAX          30
25395        ITE00100550  18641206             TMAX          31
25470        ITE00100550  18641207             TMAX          23
25545        ITE00100550  18641208             TMAX          39
25620        ITE00100550  18641209             TMAX          65
25696        ITE00100550  18641210             TMAX          60
25771        ITE00100550  18641211             TMAX          66
25844        ITE00100550  18641212             TMAX          46
25921        ITE00100550  18641213             TMAX          31
25995        ITE00100550  18641214             TMAX          44
26072        ITE00100550  18641215             TMAX          69
26147        ITE00100550  18641216             TMAX          84
26223        ITE00100550  18641217             TMAX          85
26298        ITE00100550  18641218             TMAX          76
26371        ITE00100550  18641219             TMAX          75
26445        ITE00100550  18641220             TMAX          76
26521        ITE00100550  18641221             TMAX          63
26597        ITE00100550  18641222             TMAX          50
26671        ITE00100550  18641223             TMAX          40
26746        ITE00100550  18641224             TMAX          40
26821        ITE00100550  18641225             TMAX          15
26894        ITE00100550  18641226             TMAX          16
26967        ITE00100550  18641227             TMAX          20
27042        ITE00100550  18641228             TMAX          63
27118        ITE00100550  18641229             TMAX          71
27195        ITE00100550  18641230             TMAX          50
27271        ITE00100550  18641231             TMAX          33

[366 rows x 4 columns]

In [257]:
tmax_F = newdf['obs values']*1.8 + 32
newdf = newdf.assign(tmax_F=tmax_F)

In [258]:
newdf = newdf.reset_index(drop=True)
newdf

    station identifier      data observation type  obs values  tmax_F
0          ITE00100550  18640117             TMAX         -63   -81.4
1          ITE00100550  18640118             TMAX         -50   -58.0
2          ITE00100550  18640114             TMAX         -50   -58.0
3          ITE00100550  18640113             TMAX         -43   -45.4
4          ITE00100550  18640115             TMAX         -31   -23.8
5          ITE00100550  18640103             TMAX         -28   -18.4
6          ITE00100550  18640116             TMAX         -25   -13.0
7          ITE00100550  18640112             TMAX         -25   -13.0
8          ITE00100550  18640105             TMAX         -19    -2.2
9          ITE00100550  18640211             TMAX         -18    -0.4
10         ITE00100550  18640119             TMAX         -16     3.2
11         ITE00100550  18640111             TMAX         -15     5.0
12         ITE00100550  18640106             TMAX         -13     8.6
13         ITE00100550  18640210             TMAX         -10    14.0
14         ITE00100550  18640120             TMAX          -9    15.8
15         ITE00100550  18640208             TMAX          -6    21.2
16         ITE00100550  18640107             TMAX          -4    24.8
17         ITE00100550  18640121             TMAX          -4    24.8
18         ITE00100550  18640104             TMAX           0    32.0
19         ITE00100550  18640220             TMAX           0    32.0
20         ITE00100550  18640131             TMAX           1    33.8
21         ITE00100550  18640110             TMAX           6    42.8
22         ITE00100550  18640102             TMAX           8    46.4
23         ITE00100550  18640209             TMAX           9    48.2
24         ITE00100550  18640122             TMAX           9    48.2
25         ITE00100550  18640101             TMAX          10    50.0
26         ITE00100550  18640202             TMAX          11    51.8
27         ITE00100550  18640108             TMAX          13    55.4
28         ITE00100550  18640109             TMAX          13    55.4
29         ITE00100550  18640201             TMAX          13    55.4
..                 ...       ...              ...         ...     ...
336        ITE00100550  18640909             TMAX         299   570.2
337        ITE00100550  18640623             TMAX         300   572.0
338        ITE00100550  18640706             TMAX         300   572.0
339        ITE00100550  18640803             TMAX         300   572.0
340        ITE00100550  18640713             TMAX         303   577.4
341        ITE00100550  18640717             TMAX         304   579.2
342        ITE00100550  18640727             TMAX         306   582.8
343        ITE00100550  18640718             TMAX         308   586.4
344        ITE00100550  18640821             TMAX         309   588.2
345        ITE00100550  18640624             TMAX         309   588.2
346        ITE00100550  18640728             TMAX         310   590.0
347        ITE00100550  18640716             TMAX         310   590.0
348        ITE00100550  18640804             TMAX         310   590.0
349        ITE00100550  18640807             TMAX         310   590.0
350        ITE00100550  18640823             TMAX         313   595.4
351        ITE00100550  18640730             TMAX         313   595.4
352        ITE00100550  18640731             TMAX         313   595.4
353        ITE00100550  18640622             TMAX         313   595.4
354        ITE00100550  18640720             TMAX         315   599.0
355        ITE00100550  18640723             TMAX         318   604.4
356        ITE00100550  18640816             TMAX         319   606.2
357        ITE00100550  18640810             TMAX         321   609.8
358        ITE00100550  18640722             TMAX         321   609.8
359        ITE00100550  18640721             TMAX         325   617.0
360        ITE00100550  18640806             TMAX         331   627.8
361        ITE00100550  18640805             TMAX         335   635.0
362        ITE00100550  18640801             TMAX         335   635.0
363        ITE00100550  18640808             TMAX         341   645.8
364        ITE00100550  18640802             TMAX         346   654.8
365        ITE00100550  18640809             TMAX         348   658.4

[366 rows x 5 columns]

In [259]:
newdf = newdf.sort_values(by='obs values')


print(newdf.head(1))
print(newdf.tail(1))

  station identifier      data observation type  obs values  tmax_F
0        ITE00100550  18640117             TMAX         -63   -81.4
    station identifier      data observation type  obs values  tmax_F
365        ITE00100550  18640809             TMAX         348   658.4

In [261]:
newdf.to_csv('temperatuur.csv', index=False)